name: Tests

on: 
  workflow-dispatch:
  push: 
  pull_request:

jobs:
  unit_tests:
    name: unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: checkout code
        uses: actions/checkout@v4
    
      - name: loging ghcr
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: pull image
        run: | 
            docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/nvim-essential:latest

      - name: Run tests
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace \
            ghcr.io/${{ secrets.GHCR_USERNAME }}/nvim-essential:latest \
            "sh -c "nvim --version && ./run_tests.sh"


