name: Tests

on: [push, pull_request]

jobs:
  unit_tests:
    name: unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        rev: [nightly, v0.10.0, v0.11.0]
        include:
          - os: ubuntu-22.04
            install-rg: sudo apt-get update && sudo apt-get install -y ripgrep luarocks
            install-busted: luarocks install busted

    steps:
      - uses: actions/checkout@v4

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.rev }}

      - name: Install test plugins
        shell: bash
        run: |
          set -euo pipefail

          PLUG_DIR="$HOME/.local/share/nvim/site/pack/deps/start"
          mkdir -p "$PLUG_DIR"

          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim \
            "$PLUG_DIR/plenary.nvim"
          git clone --depth 1 https://github.com/nvim-treesitter/nvim-treesitter \
            "$PLUG_DIR/nvim-treesitter"

      - name: Run tests
        run: |
          nvim --version
          tree-sitter -V
          # ./run_tests.sh

