name: format

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  format:
    name: lint lua dir
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4

    
      - name: restore cache
        id: cache
        uses: actions/cache@v3
        with: 
          path: |
            ~/.cargo/bin

          key: ${{ runner.os }}-cargo-${{ hashFiles('weekly') }}

      - name: install
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install stylua

      - name: format
        run: stylua --check lua/ --config-path=.stylua.toml
