name: format

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: create directories
        run: | 
          mkdir -p ~/.cargo/bin
          mkdir -p ~/.cargo/registry
      
      - name: restore cargo bin cache
        id: cache-stylua
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/bin
          key: stylua-bin-${{ runner.os }}-v1
          restore-keys: |
            stylua-bin-${{ runner.os }}-
            
      - name: install
        if: steps.cache-stylua.outputs.cache-hit != 'true'
        run: cargo install stylua --locked

      - name: add cargo bin to path
        run: echo "~/.cargo/bin" >> $GITHUB_PATH

      - name: format
        run: stylua --check lua/ --config-path=.stylua.toml
