name: lint

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  lint:
    name: luacheck
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
       
      - name: install
        run: |
          sudo apt update
          sudo apt install luarocks -y
          luarocks install luacheck
      
      - name: lint
        run: luacheck lua/ --globals vim
