name: lint

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  lint:
    name: luacheck
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: restore luacheck cache
        id: cache-luacheck
        uses: actions/cache@v4
        with:
          path: /usr/local/bin
          key: luacheck-bin-${{ runner.os }}-v1
          restore-keys: |
            luacheck-bin-${{ runner.os }}-

      - name: install
        if: steps.cache-luacheck.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install luarocks5.4 -y
          sudo luarocks install luacheck
      
      - name: echo
        run: which lua5.4
      - name: add luacheck to path
        run: echo "/usr/local/bin/luacheck" >> $GITHUB_PATH

      - name: lint
        run: luacheck lua/ --globals vim
