name: typos

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  lint:
    name: typos
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4
    
      - name: restore cache
        id: cache
        uses: actions/cache@v4
        with: 
          path: |
            ${{ runner.home }}/cargo/bin

          key: ${{ runner.os }}-cargo-${{ hashFiles('weekly') }}

      - name: install if not cached
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install typos-cli
  
      - name: add cargo bin to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: typos
        run: typos .
