name: typos

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  typos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Restore Cargo bin cache
        id: cache-typos
        uses: actions/cache@v4
        with: 
          path: |
            $HOME/.cargo/registry
            $HOME/.cargo/bin
          key: typos-bin-${{ runner.os }}-v1
          restore-keys: |
            typos-bin-${{ runner.os }}-

      - name: Install typos-cli if not cached
        if: steps.cache-typos.outputs.cache-hit != 'true'
        run: cargo install typos-cli --locked

      - name: Add Cargo bin to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Run typos
        run: typos .

