name: typos

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  lint:
    name: typos
    runs-on: ubuntu-latest
    
  steps:
    - name: checkout code
      uses: actions/checkout@v3
  
    - name: restore cache
      id: cache
      uses: actions/cache@v3
      with: 
        path: |
          ~/.cargo/bin

        key: ${{ runner.os }}-cargo-${{ hashFiles('weekly') }}

    - name: install
      if: steps.cache.outputs.cache-hit != 'true'
      run: cargo install typos

    - name: typos
      run: typos .

          


