name: typos

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  typos:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: create directories
        run: |
          mkdir -p ~/.cargo/registry
          mkdir -p ~/.cargo/bin

      - name: restore cargo bin cache
        id: cache-typos
        uses: actions/cache@v4
        with: 
          path: |
            ~/.cargo/registry
            ~/.cargo/bin
          key: typos-bin-${{ runner.os }}-v1
          restore-keys: |
            typos-bin-${{ runner.os }}-

      - name: install 
        if: steps.cache-typos.outputs.cache-hit != 'true'
        run: cargo install typos-cli --locked

      - name: add cargo bin to path
        run: echo "~/.cargo/bin" >> $GITHUB_PATH

      - name: run typos
        run: typos .

